//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaType as $Schema } from "./schema";
import { type ModelResult as $ModelResult } from "@zenstackhq/orm";
export type Teams = $ModelResult<$Schema, "Teams">;
export type Players = $ModelResult<$Schema, "Players">;
export type Rivalries = $ModelResult<$Schema, "Rivalries">;
export type Dates = $ModelResult<$Schema, "Dates">;
