//////////////////////////////////////////////////////////////////////////////////////////////
// DO NOT MODIFY THIS FILE                                                                  //
// This file is automatically generated by ZenStack CLI and should not be manually updated. //
//////////////////////////////////////////////////////////////////////////////////////////////

/* eslint-disable */

import { type SchemaDef, ExpressionUtils } from "@zenstackhq/orm/schema";
export class SchemaType implements SchemaDef {
    provider = {
        type: "postgresql"
    } as const;
    models = {
        Teams: {
            name: "Teams",
            fields: {
                name: {
                    name: "name",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                avatar: {
                    name: "avatar",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("teams") }] }
            ],
            idFields: ["name"],
            uniqueFields: {
                name: { type: "String" }
            }
        },
        Players: {
            name: "Players",
            fields: {
                name: {
                    name: "name",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                avatar: {
                    name: "avatar",
                    type: "String",
                    optional: true
                },
                battingStyle: {
                    name: "battingStyle",
                    type: "String",
                    optional: true
                },
                bowlingStyle: {
                    name: "bowlingStyle",
                    type: "String",
                    optional: true
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("players") }] }
            ],
            idFields: ["name"],
            uniqueFields: {
                name: { type: "String" }
            }
        },
        Rivalries: {
            name: "Rivalries",
            fields: {
                title: {
                    name: "title",
                    type: "String",
                    id: true,
                    attributes: [{ name: "@id" }]
                },
                start: {
                    name: "start",
                    type: "DateTime",
                    attributes: [{ name: "@db.Date" }, { name: "@default", args: [{ name: "value", value: ExpressionUtils.call("now") }] }],
                    default: ExpressionUtils.call("now")
                },
                end: {
                    name: "end",
                    type: "DateTime",
                    optional: true,
                    attributes: [{ name: "@db.Date" }]
                },
                dates: {
                    name: "dates",
                    type: "Dates",
                    array: true,
                    relation: { opposite: "rivalry" }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("rivalries") }] }
            ],
            idFields: ["title"],
            uniqueFields: {
                title: { type: "String" }
            }
        },
        Dates: {
            name: "Dates",
            fields: {
                date: {
                    name: "date",
                    type: "DateTime",
                    id: true,
                    attributes: [{ name: "@id" }, { name: "@db.Date" }]
                },
                title: {
                    name: "title",
                    type: "String"
                },
                rivalryId: {
                    name: "rivalryId",
                    type: "String",
                    optional: true,
                    foreignKeyFor: [
                        "rivalry"
                    ]
                },
                rivalry: {
                    name: "rivalry",
                    type: "Rivalries",
                    optional: true,
                    attributes: [{ name: "@relation", args: [{ name: "fields", value: ExpressionUtils.array([ExpressionUtils.field("rivalryId")]) }, { name: "references", value: ExpressionUtils.array([ExpressionUtils.field("title")]) }] }],
                    relation: { opposite: "dates", fields: ["rivalryId"], references: ["title"] }
                }
            },
            attributes: [
                { name: "@@map", args: [{ name: "name", value: ExpressionUtils.literal("dates") }] }
            ],
            idFields: ["date"],
            uniqueFields: {
                date: { type: "DateTime" }
            }
        }
    } as const;
    plugins = {};
}
export const schema = new SchemaType();
