/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TabRouteImport } from './routes/_tab'
import { Route as StatsRouteImport } from './routes/_stats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TabStatsIndexRouteImport } from './routes/_tab/stats.index'
import { Route as TabPlayersIndexRouteImport } from './routes/_tab/players.index'
import { Route as TabMatchesIndexRouteImport } from './routes/_tab/matches.index'
import { Route as TabExpenseIndexRouteImport } from './routes/_tab/expense.index'
import { Route as TabCompareIndexRouteImport } from './routes/_tab/compare.index'
import { Route as StatsStatsTeamsRouteImport } from './routes/_stats/stats.teams'
import { Route as StatsStatsPotmRouteImport } from './routes/_stats/stats.potm'
import { Route as StatsStatsFieldingRouteImport } from './routes/_stats/stats.fielding'
import { Route as StatsStatsBowlingRouteImport } from './routes/_stats/stats.bowling'
import { Route as StatsStatsBattingRouteImport } from './routes/_stats/stats.batting'

const TabRoute = TabRouteImport.update({
  id: '/_tab',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/_stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TabStatsIndexRoute = TabStatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => TabRoute,
} as any)
const TabPlayersIndexRoute = TabPlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => TabRoute,
} as any)
const TabMatchesIndexRoute = TabMatchesIndexRouteImport.update({
  id: '/matches/',
  path: '/matches/',
  getParentRoute: () => TabRoute,
} as any)
const TabExpenseIndexRoute = TabExpenseIndexRouteImport.update({
  id: '/expense/',
  path: '/expense/',
  getParentRoute: () => TabRoute,
} as any)
const TabCompareIndexRoute = TabCompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => TabRoute,
} as any)
const StatsStatsTeamsRoute = StatsStatsTeamsRouteImport.update({
  id: '/stats/teams',
  path: '/stats/teams',
  getParentRoute: () => StatsRoute,
} as any)
const StatsStatsPotmRoute = StatsStatsPotmRouteImport.update({
  id: '/stats/potm',
  path: '/stats/potm',
  getParentRoute: () => StatsRoute,
} as any)
const StatsStatsFieldingRoute = StatsStatsFieldingRouteImport.update({
  id: '/stats/fielding',
  path: '/stats/fielding',
  getParentRoute: () => StatsRoute,
} as any)
const StatsStatsBowlingRoute = StatsStatsBowlingRouteImport.update({
  id: '/stats/bowling',
  path: '/stats/bowling',
  getParentRoute: () => StatsRoute,
} as any)
const StatsStatsBattingRoute = StatsStatsBattingRouteImport.update({
  id: '/stats/batting',
  path: '/stats/batting',
  getParentRoute: () => StatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats/batting': typeof StatsStatsBattingRoute
  '/stats/bowling': typeof StatsStatsBowlingRoute
  '/stats/fielding': typeof StatsStatsFieldingRoute
  '/stats/potm': typeof StatsStatsPotmRoute
  '/stats/teams': typeof StatsStatsTeamsRoute
  '/compare/': typeof TabCompareIndexRoute
  '/expense/': typeof TabExpenseIndexRoute
  '/matches/': typeof TabMatchesIndexRoute
  '/players/': typeof TabPlayersIndexRoute
  '/stats/': typeof TabStatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats/batting': typeof StatsStatsBattingRoute
  '/stats/bowling': typeof StatsStatsBowlingRoute
  '/stats/fielding': typeof StatsStatsFieldingRoute
  '/stats/potm': typeof StatsStatsPotmRoute
  '/stats/teams': typeof StatsStatsTeamsRoute
  '/compare': typeof TabCompareIndexRoute
  '/expense': typeof TabExpenseIndexRoute
  '/matches': typeof TabMatchesIndexRoute
  '/players': typeof TabPlayersIndexRoute
  '/stats': typeof TabStatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_stats': typeof StatsRouteWithChildren
  '/_tab': typeof TabRouteWithChildren
  '/_stats/stats/batting': typeof StatsStatsBattingRoute
  '/_stats/stats/bowling': typeof StatsStatsBowlingRoute
  '/_stats/stats/fielding': typeof StatsStatsFieldingRoute
  '/_stats/stats/potm': typeof StatsStatsPotmRoute
  '/_stats/stats/teams': typeof StatsStatsTeamsRoute
  '/_tab/compare/': typeof TabCompareIndexRoute
  '/_tab/expense/': typeof TabExpenseIndexRoute
  '/_tab/matches/': typeof TabMatchesIndexRoute
  '/_tab/players/': typeof TabPlayersIndexRoute
  '/_tab/stats/': typeof TabStatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stats/batting'
    | '/stats/bowling'
    | '/stats/fielding'
    | '/stats/potm'
    | '/stats/teams'
    | '/compare/'
    | '/expense/'
    | '/matches/'
    | '/players/'
    | '/stats/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats/batting'
    | '/stats/bowling'
    | '/stats/fielding'
    | '/stats/potm'
    | '/stats/teams'
    | '/compare'
    | '/expense'
    | '/matches'
    | '/players'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/_stats'
    | '/_tab'
    | '/_stats/stats/batting'
    | '/_stats/stats/bowling'
    | '/_stats/stats/fielding'
    | '/_stats/stats/potm'
    | '/_stats/stats/teams'
    | '/_tab/compare/'
    | '/_tab/expense/'
    | '/_tab/matches/'
    | '/_tab/players/'
    | '/_tab/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRouteWithChildren
  TabRoute: typeof TabRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_tab': {
      id: '/_tab'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof TabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_stats': {
      id: '/_stats'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_tab/stats/': {
      id: '/_tab/stats/'
      path: '/stats'
      fullPath: '/stats/'
      preLoaderRoute: typeof TabStatsIndexRouteImport
      parentRoute: typeof TabRoute
    }
    '/_tab/players/': {
      id: '/_tab/players/'
      path: '/players'
      fullPath: '/players/'
      preLoaderRoute: typeof TabPlayersIndexRouteImport
      parentRoute: typeof TabRoute
    }
    '/_tab/matches/': {
      id: '/_tab/matches/'
      path: '/matches'
      fullPath: '/matches/'
      preLoaderRoute: typeof TabMatchesIndexRouteImport
      parentRoute: typeof TabRoute
    }
    '/_tab/expense/': {
      id: '/_tab/expense/'
      path: '/expense'
      fullPath: '/expense/'
      preLoaderRoute: typeof TabExpenseIndexRouteImport
      parentRoute: typeof TabRoute
    }
    '/_tab/compare/': {
      id: '/_tab/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof TabCompareIndexRouteImport
      parentRoute: typeof TabRoute
    }
    '/_stats/stats/teams': {
      id: '/_stats/stats/teams'
      path: '/stats/teams'
      fullPath: '/stats/teams'
      preLoaderRoute: typeof StatsStatsTeamsRouteImport
      parentRoute: typeof StatsRoute
    }
    '/_stats/stats/potm': {
      id: '/_stats/stats/potm'
      path: '/stats/potm'
      fullPath: '/stats/potm'
      preLoaderRoute: typeof StatsStatsPotmRouteImport
      parentRoute: typeof StatsRoute
    }
    '/_stats/stats/fielding': {
      id: '/_stats/stats/fielding'
      path: '/stats/fielding'
      fullPath: '/stats/fielding'
      preLoaderRoute: typeof StatsStatsFieldingRouteImport
      parentRoute: typeof StatsRoute
    }
    '/_stats/stats/bowling': {
      id: '/_stats/stats/bowling'
      path: '/stats/bowling'
      fullPath: '/stats/bowling'
      preLoaderRoute: typeof StatsStatsBowlingRouteImport
      parentRoute: typeof StatsRoute
    }
    '/_stats/stats/batting': {
      id: '/_stats/stats/batting'
      path: '/stats/batting'
      fullPath: '/stats/batting'
      preLoaderRoute: typeof StatsStatsBattingRouteImport
      parentRoute: typeof StatsRoute
    }
  }
}

interface StatsRouteChildren {
  StatsStatsBattingRoute: typeof StatsStatsBattingRoute
  StatsStatsBowlingRoute: typeof StatsStatsBowlingRoute
  StatsStatsFieldingRoute: typeof StatsStatsFieldingRoute
  StatsStatsPotmRoute: typeof StatsStatsPotmRoute
  StatsStatsTeamsRoute: typeof StatsStatsTeamsRoute
}

const StatsRouteChildren: StatsRouteChildren = {
  StatsStatsBattingRoute: StatsStatsBattingRoute,
  StatsStatsBowlingRoute: StatsStatsBowlingRoute,
  StatsStatsFieldingRoute: StatsStatsFieldingRoute,
  StatsStatsPotmRoute: StatsStatsPotmRoute,
  StatsStatsTeamsRoute: StatsStatsTeamsRoute,
}

const StatsRouteWithChildren = StatsRoute._addFileChildren(StatsRouteChildren)

interface TabRouteChildren {
  TabCompareIndexRoute: typeof TabCompareIndexRoute
  TabExpenseIndexRoute: typeof TabExpenseIndexRoute
  TabMatchesIndexRoute: typeof TabMatchesIndexRoute
  TabPlayersIndexRoute: typeof TabPlayersIndexRoute
  TabStatsIndexRoute: typeof TabStatsIndexRoute
}

const TabRouteChildren: TabRouteChildren = {
  TabCompareIndexRoute: TabCompareIndexRoute,
  TabExpenseIndexRoute: TabExpenseIndexRoute,
  TabMatchesIndexRoute: TabMatchesIndexRoute,
  TabPlayersIndexRoute: TabPlayersIndexRoute,
  TabStatsIndexRoute: TabStatsIndexRoute,
}

const TabRouteWithChildren = TabRoute._addFileChildren(TabRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRouteWithChildren,
  TabRoute: TabRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
